workspace:
  base: /code

pipeline:
  build:
    environment:
      GOPATH: /code/go
    image: amarburg/lsdslam-dev-host:latest
    commands:
          - add-apt-repository ppa:longsleep/golang-backports
          - apt-get update && apt-get install -y ca-certificates golang-go libavformat-dev
          - ./fips set config linux-make-unittest
          - ./fips build
