workspace:
  base: /code
  path: lsd-slam/libvideoio-go

pipeline:
  build:
    environment:
      - GOPATH=/code/go
    image: amarburg/lsdslam-dev-host:latest
    pull:  true
    commands:
      - apt-get update && apt-get install -y golang-go
      - ./fips fetch
      - ./fips set config linux-make-unittest
      - ./fips build

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status:
        - success
        - failure
