pipeline:
  build:
    image: amarburg/lsdslam-dev-host:latest
    commands:
          - apt-get update && apt-get install -y ca-certificates
          - ./fips set config linux-make-unittest
          - ./fips build
