workspace:
  base: /code

pipeline:
  build:
    environment:
      - GOPATH=/code/go
    image: amarburg/lsdslam-dev-host:latest
    pull:  true
    commands:
          - apt-get update && apt-get install -y golang-go
          - ./fips set config linux-make-unittest
          - ./fips build
